Web/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('WebApp.urls',namespace='WebApp')),
    path('basket/',include('basket.urls', namespace='basket'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)

WebApp/urls.py
from django.urls import path
from . import views


app_name ='WebApp'
urlpatterns = [
    path('', views.myHome, name='myHome'),
    path('item/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search/<slug:category_slug>', views.category_list, name='category_list'),
    path('search_food', views.myHome, name='search_food')
    # path('about', views.about, name='about'),
    # path('menu', views.menu, name='menu'),
    # path('booking', views.booking, name='booking'),   
]

basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'
urlpatterns = [
    path('', views.basket_summary, name ='basket_summary'),
    path('add/', views.basket_add, name = 'basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

WebApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.query import QuerySet
from django.urls import reverse

# Create your models here.



# class ProductManager(models.Manager):
#     def get_queryset(self):
#         return super(ProductManager, self).get_queryset().filter(is_active=True)
    

class Category(models.Model):
    name = models.CharField(max_length = 200, null= False)
    slug = models.SlugField(max_length= 200, unique = True)


    class Meta:
        verbose_name_plural ='categories'

    
    def __str__(self):
        return self.name
    
class Products(models.Model):
    category = models.ForeignKey(Category, related_name='product',on_delete =models.CASCADE)
    created_by =models.ForeignKey(User, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length =200)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/')
    slug = models.SlugField(max_length=200)
    price = models.DecimalField(max_digits=12,decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    

    
    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created_on',)

    def get_absolute_url(self):
        return reverse('WebApp:product_detail', args=[self.slug])

    
    def __str__(self):
        return self.title

basket/models.py
from django.db import models

# Create your models here.

WebApp/forms.py
from django import forms

class search_details(forms.Form):
    query = forms.CharField(label='search food or vendor',max_length=250)

WebApp/views.py
from django.shortcuts import get_object_or_404, render
from .models import *
from .forms import *


# Create your views here.



def myHome(request):
 
    products = Products.objects.all()
    categories = Category.objects.all()

    # Check if a category is selected
    selected_category = request.GET.get('category')
    searched = request.POST.get('searched')

    if selected_category:
        # Filter food items by the selected category
        products = Products.objects.filter(category__slug=selected_category)
        return products
    elif searched:
        products = Products.objects.filter(title__icontains=searched)

    return render (request, 'index.html', {'products':products,'categories':categories})


def product_detail(request, slug):
    product = get_object_or_404(Products, slug=slug, in_stock=True)
    return render(request, 'post_detail.html',{'product': product})

def category_list(request, category_slug):
    category = get_object_or_404(Category, slug =category_slug)
    products = Products.objects.filter(category=category)
    return render (request, 'category.html',{'category':category, 'products':products})



# def about(request):
#     return render (request, 'about.html')

# def menu(request):
#     return render (request, 'menu.html')

# def booking(request):
#     return render (request, 'book.html')

basket/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from .basket import Basket
from  WebApp.models import Products
from django.http import JsonResponse
# Create your views here.

def basket_summary(request):
    basket = Basket(request)
    return render(request, 'summary.html', {'basket':basket})


    """
    The `basket_add` function adds a product to the user's shopping basket and returns the updated
    quantity of items in the basket as a JSON response.
    """
def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Products, id=product_id)
        basket.add(product=product, qty=product_qty)

        basketqty = basket.__len__()
        response = JsonResponse({'qty': basketqty})
        return response

  



def basket_delete(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        basket.delete(product=product_id)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response


def basket_update(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        basket.update(product=product_id, qty=product_qty)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- about section -->
<section class="about_section layout_padding">
    <div class="container  ">

      <div class="row">
        <div class="col-md-6 ">
          <div class="img-box">
              <img src="{% static 'images/about-img.png'%}" alt="">
          </div>
        </div>
        <div class="col-md-6">
          <div class="detail-box">
            <div class="heading_container">
              <h2>
                We Are Feane
              </h2>
            </div>
            <p>
              There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration
              in some form, by injected humour, or randomised words which don't look even slightly believable. If you
              are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in
              the middle of text. All
            </p>
            <a href="">
              Read More
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>
  {%endblock}

  <!-- end about section -->

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="{% static 'images/favicon.png'%}" type="">
  <title>
    {% block title %} 

    {% endblock %}
  </title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
  integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"
  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css'%}" />

  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css"
    href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
  <!-- nice select  -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css"
    integrity="sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ=="
    crossorigin="anonymous" />
  <!-- font awesome style -->
  <link href="{% static 'css/font-awesome.min.css'%}" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css'%}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css'%}" rel="stylesheet" />


</head>

<body>

  <div class="hero_area">
    <div class="bg-box">
      <img src="{% static 'images/hero-bg.jpg'%}" alt="">
    </div>
    <!-- header section strats -->
    <header class="header_section sticky-top">
      <div class="container">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand" href="{% url 'WebApp:myHome' %}">
            <span>
              BleNourishNet
            </span>
          </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""> </span>
          </button>



          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav  mx-auto ">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'WebApp:myHome' %}">Home <span class="sr-only">(current)</span></a>
              </li>


              <li class="nav-item">
                <a class="nav-link" href="book.html">Book</a>
              </li>


              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="menu.html" id="navbarDropdown" role="button"
                  data-bs-toggle="dropdown" aria-expanded="false">
                  Menu
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="">All</a></li>
                  {% for category in categories %}
                  <li>
                    <a class="dropdown-item" href="{% url 'WebApp:category_list' category.slug %}">{{ category.name }}</a>
                  </li>
                  {% endfor %}
                </ul>
              </li>
          
              <li class="nav-item">
                <a class="nav-link" type="button" role="button" href="{% url 'basket:basket_summary' %} "
                class="btn btn-outline-secondary border-0 basket-btn">
                <!-- <div class="d-inline-flex">0</div> -->

                {% with total_qty=basket|length %}
                  <div id="basket-qty" class="d-inline-flex">
                    {% if total_qty > 0 %}
                    {{ total_qty }}
                    {% else %}
                       0
                    {% endif %}
                  </div>
                {% endwith %}
                <div>
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                        class="bi bi-cart3" viewBox="0 0 16 16">
                        <path
                            d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                    </svg>
                </div>
                
              </li> 
            
              <div class="user_option">
                <a href="" class="user_link">
                  <i class="fa fa-user" aria-hidden="true"></i>
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="">Order</a></li>
                  <li><a class="dropdown-item" href="">Payment</a>Payment</li>
                </ul>

                

                <a href="" class="order_online">
                  Order Online
                </a>
              </div>
            </ul>



          </div>
        </nav>
      </div>
    </header>
    <!-- end header section -->
    <!-- slider section -->
    <section class="slider_section ">
      <div id="customCarousel1" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="container ">
              <div class="row">
                <div class="col-md-7 col-lg-6 ">
                  <div class="detail-box">
                    <h1>
                      Food Web
                    </h1>
                    <p>
                      "BleNourishNet" is not just an app for buying and selling food; it's a platform that promotes
                      sustainable and ethical food practices while supporting local businesses. Whether you're a vendor
                      looking to reach a wider audience or a consumer wanting to make eco-conscious food choices, this
                      app
                      is your gateway to a more sustainable food nurishment and niche.
                    </p>
                    <form class="d-flex" method="POST" action="{% url 'WebApp:search_food' %}">
                      {% csrf_token %}
                      <input class="form-control me-2 " type="search" placeholder="search food" name="searched">
                      <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="carousel-item ">
            <div class="container ">
              <div class="row">
                <div class="col-md-7 col-lg-6 ">
                  <div class="detail-box">
                    <h1>
                      Food Web
                    </h1>
                    <p>
                      "BleNourishNet" is not just an app for buying and selling food; it's a platform that promotes
                      sustainable and ethical food practices while supporting local businesses. Whether you're a vendor
                      looking to reach a wider audience or a consumer wanting to make eco-conscious food choices, this
                      app
                      is your gateway to a more sustainable food nurishment and niche.
                    </p>
                    <form class="d-flex">
                      <input class="form-control me-2 " type="search" placeholder="search food" aria-label="search" name="searched">
                      <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <div class="container ">
              <div class="row">
                <div class="col-md-7 col-lg-6 ">
                  <div class="detail-box">
                    <h1>
                      Food Web
                    </h1>
                    <p>
                      "BleNourishNet" is not just an app for buying and selling food; it's a platform that promotes
                      sustainable and ethical food practices while supporting local businesses. Whether you're a vendor
                      looking to reach a wider audience or a consumer wanting to make eco-conscious food choices, this
                      app
                      is your gateway to a more sustainable food nurishment and niche.
                    </p>
                    <form class="d-flex">
                      <input class="form-control me-2 " type="search" placeholder="search food" aria-label="search" name="searched">
                      <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="container">
          <ol class="carousel-indicators">
            <li data-target="#customCarousel1" data-slide-to="0" class="active"></li>
            <li data-target="#customCarousel1" data-slide-to="1"></li>
            <li data-target="#customCarousel1" data-slide-to="2"></li>
          </ol>
        </div>
      </div>

    </section>
    <!-- end slider section -->
  </div>

  <!-- offer section -->

  {% block content %}



  {% endblock %}

  <!-- footer section -->
  <footer class="footer_section">
    <div class="container">
      <div class="row">
        <div class="col-md-4 footer-col">
          <div class="footer_contact">
            <h4>
              Contact Us
            </h4>
            <div class="contact_link_box">
              <a href="">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <span>
                  Location
                </span>
              </a>
              <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  Call +234 08165390038
                </span>
              </a>
              <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  meetonyinyechukwu@gmail.com
                </span>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-4 footer-col">
          <div class="footer_detail">
            <a href="" class="footer-logo">
              BleNourishNet
            </a>
            <p>
              Necessary, making this the first true generator on the Internet. It uses a dictionary of
              over 200 Latin words, combined with
            </p>
            <div class="footer_social">
              <a href="">
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-linkedin" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-pinterest" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-4 footer-col">
          <h4>
            Opening Hours
          </h4>
          <p>
            Everyday
          </p>
          <p>
            10.00 Am -10.00 Pm
          </p>
        </div>
      </div>
      <div class="footer-info">
        <p>
          &copy; <span id="displayYear"></span> All Rights Reserved By
          <a href="https://html.design/">Free Html Templates</a><br><br>
          &copy; <span id="displayYear"></span> Distributed By
          <a href="https://themewagon.com/" target="_blank">ThemeWagon</a>
        </p>
      </div>
    </div>
  </footer>
  <!-- footer section -->

  <!-- jQery -->
  
  
  <!-- popper js -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
  <!-- bootstrap js -->
  <script src="{% static 'js/bootstrap.js'%}"></script>
  <!-- owl slider -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
  </script>
  <!-- isotope js -->
  <script src="https://unpkg.com/isotope-layout@3.0.4/dist/isotope.pkgd.min.js"></script>
  <!-- nice select -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js"></script>
  <!-- custom js -->
  <script src="{% static 'js/custom.js'%}"></script>
  <!-- Google Map -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
  </script>
  <!-- End Google Map -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
 

</body>

</html>

templates/summary.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Basket Summary{% endblock %}
{% block content %}


<section class="h-100 gradient-custom">
    <div class="container py-5">
        <div class="row d-flex justify-content-center my-4">

            {% if basket|length == 0 %}
            <div class="col-md-6">

                <div class="card mb-4">
                    <div class="card-body">
                        <p><strong>Your basket is empty</strong></p>
                        <a href="{% url 'WebApp:myHome' %}">Continue Shopping</a>

                    </div>
                </div>

            </div>
            {% else %}
            <div class="col-md-6">
                <div class="card mb-4">
                    <div class="card-header py-3">
                        <h5 class="mb-0">Basket Summary</h5>
                    </div>
                    {% for item in basket %}
                    {% with product=item.product %}
                    <div class="card-body product-item" data-index="{{product.id}}">
                        <!-- Single item -->
                        <div class="row">

                            <div class="col-lg-3 col-md-12 mb-4 mb-lg-0">
                                <!-- Image -->
                                <div class="bg-image hover-overlay hover-zoom ripple rounded"
                                    data-mdb-ripple-color="light">

                                    <img src="{{ product.image.url }}" class="w-100" alt="{{product.title}}" />
                                    <a href="#!">
                                        <div class="mask" style="background-color: rgba(251, 251, 251, 0.2)">
                                        </div>
                                    </a>
                                </div>
                                <!-- Image -->
                            </div>

                            <div class="col-lg-5 col-md-6 mb-4 mb-lg-0">
                                <!-- Data -->
                                <p><strong>{{product.title}}</strong></p>

                                <button type="button" id="update-button" data-index="{{product.id}}"
                                    class="update-button text-decoration-none small ps-3 btn btn-success">Update</button>


                                <button type="button" id="delete-button" data-index="{{product.id}}"
                                    class="delete-button text-decoration-none small btn btn-danger">Delete</button>
                                <!-- Data -->
                            </div>

                            <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
                                <!-- Quantity -->
                                <div class="">
                                    <select id="select{{product.id}}" class="form-select w-50"
                                        aria-label="Default select example">
                                        <option value="" selected disabled hidden>{{item.qty}}</option>

                                        <option value="">1</option>
                                        <option value="">2</option>
                                        <option value="">3</option>
                                        <option value="">4</option>
                                        <option value="">5</option>
                                        <option value="">6</option>
                                        <option value="">7</option>
                                        <option value="">8</option>
                                        <option value="">9</option>
                                        <option value="">10</option>

                                    </select>

                                </div>
                                <!-- Quantity -->

                                <!-- Price -->
                                <p class="text-start text-md-center">
                                    <strong>&#8358; {{product.price}}</strong>
                                </p>
                                <!-- Price -->
                            </div>

                        </div>
                        <!-- Single item -->

                        <hr class="my-4" />


                    </div>
                    {% endwith %}
                    {% endfor %}
                </div>
                <div class="card mb-4">
                    <div class="card-body">
                        <p><strong>Expected shipping delivery</strong></p>
                        <p class="mb-0">3 hours after order has been placed</p>
                    </div>
                </div>
                <div class="card mb-4 mb-lg-0">
                    <div class="card-body">
                        <p><strong>We accept</strong></p>
                        <img class="me-2" width="45px"
                            src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/visa.svg"
                            alt="Visa" />
                        <img class="me-2" width="45px"
                            src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/amex.svg"
                            alt="American Express" />
                        <img class="me-2" width="45px"
                            src="https://mdbcdn.b-cdn.net/wp-content/plugins/woocommerce-gateway-stripe/assets/images/mastercard.svg"
                            alt="Mastercard" />

                    </div>
                </div>
            </div>
            {% endif %}

            <div class="col-md-4">
                <div class="card mb-4">
                    <div class="card-header py-3">
                        <h5 class="mb-0">Summary</h5>
                    </div>
                    <div class="card-body">
                        <ul class="list-group list-group-flush">
                            <li
                                class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
                                Products
                                <span id="subtotal">&#8358; {{basket.get_subtotal_price}}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                                Shipping
                                <span>&#8358; 1000.00</span>
                            </li>
                            <li
                                class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                                <div>
                                    <strong>Total amount</strong>
                                    <strong>
                                        <p class="mb-0">(including VAT)</p>
                                    </strong>
                                </div>
                                <span id="total"><strong>&#8358; {{basket.get_total_price}}</strong></span>
                            </li>
                        </ul>

                        <button type="button" class="btn btn-primary btn-lg btn-block">
                            Checkout Securely
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    // Delete Item
    $(document).on('click', '.delete-button', function (e) {
        e.preventDefault();
        var prodid = $(this).data('index');
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_delete" %}',
            data: {
                productid: $(this).data('index'),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
                $('.product-item[data-index="' + prodid + '"]').remove();
                document.getElementById("subtotal").innerHTML = json.subtotal;
                document.getElementById("basket-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) { }
        });
    })

    // Update Item
    $(document).on('click', '.update-button', function (e) {
        e.preventDefault();
        var prodid = $(this).data('index');
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_update" %}',
            data: {
                productid: $(this).data('index'),
                productqty: $('#select' + prodid + ' option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
                document.getElementById("basket-qty").innerHTML = json.qty
                document.getElementById("subtotal").innerHTML = json.subtotal
            },
            error: function (xhr, errmsg, err) { }
        });
    })
</script>

{% endblock %}